//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Client.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDD_DLG_GROUP                   128
#define IDD_DLG_INFO                    129
#define IDD_DLG_SCREENSPY               130
#define IDR_MAINFRAME                   131
#define IDD_DLG_BUILD                   132
#define IDR_FILEMANAGER                 133
#define IDR_MENU_TRAY                   134
#define IDB_TREE_IMAGES                 135
#define IDB_TOOL_BMP                    136
#define IDB_PNG_MSG                     137
#define IDB_PNG_SHUT                    138
#define IDB_PNG_FILE                    139
#define IDB_PNG_PM                      140
#define IDC_DRAG                        141
#define IDC_CURSOR2                     142
#define IDC_MUTI_DRAG                   143
#define IDC_DOT                         144
#define IDD_DLG_TRANSFERMODE            145
#define IDI_SCREENSYP                   146
#define ID_STAUTS_PORT                  147
#define IDD_DLG_FILEMANAGER             148
#define ID_MENU_FILE                    149
#define IDR_TOOLBAR1                    150
#define ID_TOOL_HOME                    151
#define IDI_ICOFILE                     152
#define ID_TOOL_SET                     153
#define IDB_TOOLBAR_ENABLE              154
#define ID_TOOL_FUC                     155
#define IDB_TOOLBAR_DISABLE             156
#define ID_TOOL_ABOUT                   157
#define IDR_MENU_BATCH                  158
#define IDD_DLG_SHELL                   158
#define IDR_MENU_TOOL                   159
#define IDI_CMDSHELL                    159
#define IDR_MENU_TOOL1                  160
#define IDR_MENU_LIST                   161
#define IDR_TOOLBAR2                    162
#define IDR_LOCAL_VIEW                  163
#define IDR_REMOTE_VIEW                 164
#define IDB_BITMAP_MENU                 166
#define IDB_PNG1                        167
#define IDB_PNG_BUILD                   168
#define IDB_PNG2                        169
#define IDB_PNG_TOOL                    170
#define IDB_BITMAP1                     171
#define IDB_BITMAP_KEHU                 172
#define IDB_BITMAP_RECV                 173
#define IDB_BITMAP_SEND                 174
#define IDB_PNG_ABOUT                   175
#define IDR_MENU_OPTIONS                176
#define IDD_DIALOG1                     176
#define IDD_DLG_URLHISTORY              176
#define IDD_DIALOG2                     177
#define IDB_SPLASHB                     178
#define IDB_SPLASH                      178
#define IDD_DLG_SYSTEM                  179
#define IDB_BITMAP2                     179
#define IDI_SYSTEM                      180
#define IDB_PNG3                        180
#define IDB_PNG_LOGIN                   180
#define IDR_MENU_SLIST                  181
#define IDD_DIALOG3                     181
#define IDR_TOOLBAR4                    184
#define IDR_TOOLBAR3                    185
#define IDI_KEYBOARD                    186
#define IDB_TOOLBAR_SEARCH              186
#define IDD_DLG_MESSAGEBOX              187
#define IDD_DLG_SERVICE                 188
#define IDR_MENU_SERVICE                189
#define IDI_ICONSERVICE                 190
#define IDD_DLG_SERVICE_INFO            191
#define IDD_DLG_REGEDIT                 192
#define IDR_MENU_REGEDIT_MAIN           193
#define IDR_MENU_REGEDIT_TREE           194
#define IDD_DLG_REGEDIT_TEXT            195
#define IDR_MENU_SERVERLIST             196
#define IDD_DLG_KEYBOARD                197
#define IDR_MENU_SYSTEMMANAGER          198
#define IDD_DLG_LOGIN1                  198
#define IDR_MENU_REGEDIT_LIST           199
#define IDD_DLG_SCREENSPY1              199
#define IDI_ICON_REGEDIT                217
#define IDI_ICON1                       224
#define IDI_ICON2                       226
#define IDI_ICON3                       227
#define IDI_ICON4                       228
#define IDI_ICON5                       229
#define IDI_ICON6                       230
#define IDI_ICON_TEXTCHAT               246
#define IDC_TREE_GROUP                  1000
#define IDC_CHARTCONTRO                 1001
#define IDC_LOCAL_PATH                  1002
#define IDC_STATIC_HOST                 1003
#define IDC_REMOTE_PATH                 1004
#define IDC_STATIC_NAME                 1005
#define IDC_STATIC_NAME2                1006
#define IDC_LIST_REMOTE                 1007
#define IDC_STATIC_CPU                  1008
#define IDC_LIST_LOCAL                  1009
#define IDC_STATIC_CPU2                 1010
#define IDC_LIST_REMOTE_SEARCH          1011
#define IDC_OVERWRITE                   1012
#define IDC_STATIC_MEM                  1013
#define IDC_EDIT                        1013
#define IDC_OVERWRITE_ALL               1014
#define IDC_STATIC_MEM2                 1015
#define IDC_ADDITION                    1016
#define IDC_STATIC_OS                   1017
#define IDC_ADDITION_ALL                1018
#define IDC_STATIC_OS2                  1019
#define IDC_TIPS                        1020
#define IDC_LIST                        1021
#define IDC_STATIC_REMOTE               1022
#define IDC_STATIC_USER2                1023
#define IDC_JUMP                        1024
#define IDC_STATIC_IP                   1025
#define IDC_STATIC_IP2                  1026
#define IDC_JUMP_ALL                    1027
#define IDC_BTN_PM                      1028
#define IDC_CANCEL                      1029
#define IDC_LIST1                       1029
#define IDC_LIST_INFO                   1029
#define IDC_LIST_URL                    1029
#define IDC_BTN_MSG                     1030
#define IDC_BTN_BUILD                   1031
#define IDC_EDIT1                       1031
#define IDC_EDIT_KM                     1031
#define IDC_BTN_FILE                    1032
#define IDC_EDIT_USER2                  1032
#define IDC_RADIO1                      1033
#define IDC_BTN_SHUT                    1034
#define IDC_RADIO2                      1035
#define IDC_STATIC_BUILD                1036
#define IDC_EDIT3                       1036
#define IDC_STATIC_BUILD2               1037
#define IDC_COMBO1                      1037
#define IDC_STATIC_PIC                  1038
#define IDC_STATIC_PM                   1039
#define IDC_EDIT_PORT                   1040
#define IDC_STATIC_MSG                  1041
#define IDC_STATIC_FILE                 1042
#define IDC_STATIC_SHUT                 1043
#define IDC_STATIC_NET                  1044
#define IDC_STATIC_SEND                 1045
#define IDC_STATIC_RECV                 1046
#define IDC_BUTTON_PREVIEW              1077
#define IDC_EDIT_CAPTION                1079
#define IDC_COMBO_MSG_TYPE              1080
#define IDC_COMBO_BUTTON_TYPE           1081
#define IDC_EDIT_TEXT                   1082
#define IDC_BUTTON_CONTINUE             1083
#define IDC_TAB                         1084
#define IDC_STATIC_USER                 1085
#define IDC_EDIT_SERDISPLAYNAME         1105
#define IDC_EDIT_SERDESCRIPTION         1106
#define IDC_EDIT_FILEPATH               1107
#define IDC_EDIT_SERNAME                1109
#define IDC_STATIC_TEXT                 1110
#define IDC_BUTTON_START                1111
#define IDC_BUTTON_STOP                 1112
#define IDC_BUTTON_PAUSE                1113
#define IDC_BUTTON_MSTSC                1114
#define IDC_BUTTON_USE                  1115
#define IDC_COMBO_RUNWAY                1116
#define IDC_BUTTON_CHANAGEPORT          1117
#define IDC_TREE                        1118
#define IDC_BUTTON_OPEN3389             1119
#define IDC_EDIT_NAME                   1120
#define IDC_EDIT_DATE                   1121
#define ID_OPTIONS_FONT_SYSTEM          32771
#define ID_OPTIONS_FONT_NORMAL          32772
#define ID_OPTIONS_FONT_LARGE           32773
#define ID_OPTIONS_FONT_EXTRALARGE      32774
#define ID_OPTIONS_FONT_AUTORESIZEICONS 32775
#define IDM_TRANSFER                    32776
#define ID_OPTIONS_FONT_DPI_ICON_SCALING 32777
#define ID_OPTIONS_STYLE_OFFICE2010BLUE 32778
#define IDM_RENAME                      32779
#define ID_OPTIONS_STYLE_OFFICE2010SILVER 32780
#define ID_OPTIONS_STYLE_OFFICE2010BLACK 32781
#define IDM_DELETE                      32782
#define ID_OPTIONS_STYLE_OFFICE2013WORD 32783
#define ID_OPTIONS_STYLE_OFFICE2016WORD 32784
#define IDM_NEWFOLDER                   32785
#define ID_OPTIONS_STYLE_WINDOWS7SCENIC 32786
#define IDT_LOCAL_PREV                  32787
#define ID_OPTIONS_FRAMETHEME           32788
#define IDT_LOCAL_COPY                  32789
#define IDT_LOCAL_DELETE                32790
#define IDT_LOCAL_NEWFOLDER             32791
#define IDT_REMOTE_PREV                 32792
#define ID_MENUITEM_SHOW                32793
#define IDT_REMOTE_COPY                 32794
#define ID_MENUITEM_HIDE                32795
#define IDT_REMOTE_DELETE               32796
#define ID_FILE_BUILD                   32797
#define ID_FILE_SETTING                 32798
#define IDT_REMOTE_NEWFOLDER            32800
#define ID_TREE_INFO                    32801
#define IDT_REMOTE_STOP                 32802
#define ID_TREE_                        32803
#define ID_BATCH_SHUT                   32804
#define IDM_LOCAL_BIGICON               32805
#define ID_BATCH_RESTART                32806
#define IDM_LOCAL_SMALLICON             32807
#define ID_BATCH_LOGUT                  32808
#define IDM_LOCAL_LIST                  32809
#define ID_BATCH_LOGOUT                 32810
#define IDM_LOCAL_REPORT                32811
#define ID_BATCH_SELC                   32812
#define IDM_REMOTE_BIGICON              32813
#define ID_BATCH_SELECT_ALL             32814
#define IDM_REMOTE_SMALLICON            32815
#define ID_BATCH_UNSELECT               32816
#define IDM_REMOTE_LIST                 32817
#define ID_TOOL_FILE                    32818
#define IDM_REMOTE_REPORT               32819
#define ID_TOOL_PM                      32820
#define IDM_REFRESH                     32821
#define ID_TOOL_SYSTEM                  32822
#define ID_MENUITEM_KILLPROCESS         32823
#define IDM_LOCAL_OPEN                  32824
#define ID_MENUITEM_REFRESH_SLIST       32825
#define ID_TOOL_SERVICE                 32826
#define IDM_REMOTE_OPEN_SHOW            32827
#define ID_TOOL_SYSINFO                 32828
#define IDM_REMOTE_OPEN_HIDE            32829
#define ID_TOOL_REGEDIT                 32830
#define ID_TOOL_BATCH                   32831
#define ID_TOOL_KEYBOARD                32832
#define ID_FILE_USER                    32833
#define ID_TOOL_REMOVE                  32834
#define IDT_LOCAL_STOP                  32835
#define ID_MENUITEM_COPY                32836
#define ID_TOOL_NEWGROUP                32837
#define ID_TOOL_CHANGEGROUP             32838
#define ID_LIST_FILE                    32839
#define ID_LIST_PM                      32840
#define ID_LIST_SYSTEM                  32841
#define ID_LIST_SERVICE                 32842
#define ID_LIST_SYSINFO                 32843
#define ID_LIST_KEYBOARD                32844
#define ID_LIST_REGEDIT                 32845
#define ID_TOOL_REBOR                   32845
#define ID_LIST_BATCH                   32846
#define ID_TOOL_RESTART                 32846
#define ID_MENUITEM_ACTIVE_USER         32847
#define ID_TOOL_LOGOUT                  32847
#define ID_SEARCH_TEXT                  32848
#define ID_TOOL_SHUT                    32848
#define ID_MENUITEM_DISABLE_USER        32849
#define ID_TOOL_SENDMSG                 32849
#define ID_SEARCH_START                 32850
#define ID_32850                        32850
#define ID_MENUITEM_CHANGE_PASS         32851
#define ID_32851                        32851
#define ID_SEARCH_STOP                  32852
#define ID_TOOL_NEW_CROUP               32852
#define ID_MENUITEM_DEL_USER            32853
#define ID_TOOL_NEWCROUP                32853
#define ID_SEARCH_RESULT                32854
#define ID_TOOL_DEL_CROUP               32854
#define ID_MENUITEM_DISCONNECT_USER     32855
#define ID_TOOL_CHANGEREMARK            32855
#define ID_MENUITEM_OPEN_FILEPATH       32856
#define ID_TOOL_REMOTESHELL             32856
#define ID_MENUITEM_LOGOFF_USER         32857
#define ID_MENUITEM_MOVE                32858
#define ID_MENUITEM_ADD_USER            32859
#define ID_MENUITEM_PASTE               32860
#define ID_SEARCH_SUBFOLDER             32861
#define ID_MENUITEM_START_SERVICE       32862
#define ID_MENUITEM_STOP_SERVICE        32863
#define ID_MENUITEM_PAUSE_SERVICE       32864
#define ID_MENUITEM_REGAIN_SERVICE      32865
#define ID_MENUITEM_REBOOT_SERVICE      32866
#define ID_MENUITEM_WINDOW_RESTORED     32867
#define ID_MENUITEM_PROPERTIES_SERVICE  32868
#define ID_MENUITEM_WINDOW_HIDE         32869
#define ID_MENUITEM_DEL_SERVICE         32870
#define ID_MENUITEM_WINDOW_CLOSE        32871
#define ID_MENUITEM_REFRESH_SERVICE     32872
#define ID_MENUITEM_REGEXIT             32873
#define ID_MENUITEM_WINDOW_MAX          32874
#define ID_MENUITEM_TREE_NEW            32875
#define ID_MENUITEM_WINDOW_MIN          32876
#define ID_MENUITEM_TREE_REFRESH        32877
#define ID_MENUITEM_KILLANDDEL          32878
#define ID_MENUITEM_TREE_DEL            32879
#define ID_MENUITEM_TREE_COPYNAME       32880
#define ID_MENUITEM_TREE_ADDTOFAVORITE  32881
#define ID_MENUITEM_REG_EDIT            32882
#define ID_MENUITEM_REG_DEL             32883
#define ID_MENUITEM_S_LOGOFF            32884
#define ID_MENUITEM_REG_STR             32985
#define ID_MENUITEM_S_REBOOT            32986
#define ID_MENUITEM_REG_DWORD           32987
#define ID_MENUITEM_S_SHUTDOWN          32988
#define ID_MENUITEM_EXSTR               32989
#define ID_STAUTS_TIMEOUT               59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32857
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
